import { sanitizeRichText } from '../../lib/validation/sanitize'
import { createButton, createCard } from '../../lib/builder/defaultBlocks'
import { Button, Field, TextArea, TextInput } from './ui.jsx'

export default function BuilderRightInspector({ site, selectedPage, selectedSection, selectedSectionIndex, updatePage, updateSection, moveSection, selectMediaForSection, breadcrumb }) {
  if (!selectedSection) return <aside className="overflow-auto border-l border-slate-200 bg-white p-5 shadow-2xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-sky-500">Inspector</p><h2 className="mt-2 text-xl font-black">Page settings</h2><PageSettings selectedPage={selectedPage} updatePage={updatePage} /></aside>
  const content = selectedSection.content || {}
  return <aside className="overflow-auto border-l border-slate-200 bg-white p-5 shadow-2xl"><p className="text-xs font-black uppercase tracking-[0.25em] text-sky-500">Inspector</p><h2 className="mt-2 text-xl font-black">Selected {selectedSection.type}</h2><p className="mt-1 rounded-xl bg-slate-50 px-3 py-2 text-xs font-bold text-slate-600">Editing: {breadcrumb}</p><p className="mt-1 text-sm text-slate-500">Use the canvas for direct editing. These controls are only for the selected item.</p><div className="mt-5 space-y-5"><details className="rounded-2xl border border-slate-200 p-4"><summary className="cursor-pointer font-black">Page SEO & URL</summary><div className="mt-4"><PageSettings selectedPage={selectedPage} updatePage={updatePage} /></div></details><Field label="Section title"><TextInput value={selectedSection.title} onChange={(event) => updateSection((section) => { section.title = event.target.value })} /></Field><Field label="Plain paragraph"><TextArea value={content.text || ''} onChange={(event) => updateSection((section) => { section.content.text = event.target.value })} /></Field>{selectedSection.type === 'richText' && <Field label="Rich text"><TextArea value={content.richText || ''} onChange={(event) => updateSection((section) => { section.content.richText = sanitizeRichText(event.target.value) })} /></Field>}<DesignSettings selectedSection={selectedSection} updateSection={updateSection} /><MediaChooser site={site} selectedSection={selectedSection} selectMediaForSection={selectMediaForSection} /><CardsEditor selectedSection={selectedSection} updateSection={updateSection} /><ButtonsEditor selectedSection={selectedSection} updateSection={updateSection} /><div className="grid grid-cols-2 gap-2"><Button tone="light" onClick={() => moveSection(selectedSectionIndex, selectedSectionIndex - 1)}>Move up</Button><Button tone="light" onClick={() => moveSection(selectedSectionIndex, selectedSectionIndex + 1)}>Move down</Button></div></div></aside>
}
function PageSettings({ selectedPage, updatePage }) { return <div className="space-y-3"><Field label="Page title"><TextInput value={selectedPage.title} onChange={(event) => updatePage((page) => { page.title = event.target.value })} /></Field><Field label="Page URL / slug"><TextInput value={selectedPage.slug} onChange={(event) => updatePage((page) => { page.slug = event.target.value.replace(/^\//, '') })} /></Field><Field label="SEO title"><TextInput value={selectedPage.seoTitle || ''} onChange={(event) => updatePage((page) => { page.seoTitle = event.target.value })} /></Field><Field label="SEO description"><TextArea value={selectedPage.seoDescription || ''} onChange={(event) => updatePage((page) => { page.seoDescription = event.target.value })} /></Field><Button tone="light" onClick={() => updatePage((page) => { page.hidden = !page.hidden })}>{selectedPage.hidden ? 'Show page' : 'Hide page'}</Button></div> }
function DesignSettings({ selectedSection, updateSection }) { return <div className="grid grid-cols-2 gap-3"><Field label="Background"><TextInput type="color" value={selectedSection.background || '#ffffff'} onChange={(event) => updateSection((section) => { section.background = event.target.value })} /></Field><Field label="Spacing"><select className="w-full rounded-xl border border-slate-200 p-2 text-sm" value={selectedSection.padding || 'normal'} onChange={(event) => updateSection((section) => { section.padding = event.target.value })}><option>small</option><option>normal</option><option>large</option></select></Field></div> }
function MediaChooser({ site, selectedSection, selectMediaForSection, breadcrumb }) { return <div><p className="mb-2 text-[11px] font-black uppercase tracking-wide text-slate-500">Visual media picker</p><div className="grid max-h-72 grid-cols-3 gap-2 overflow-auto rounded-2xl border border-slate-200 bg-slate-50 p-2">{site.media.map((item) => <button key={item.id} onClick={() => selectMediaForSection(item.id)} className={`overflow-hidden rounded-xl border bg-white text-left shadow-sm ${selectedSection.content?.imageId === item.id || selectedSection.content?.mediaIds?.includes(item.id) ? 'border-sky-500 ring-2 ring-sky-200' : 'border-slate-200'}`}>{item.type === 'image' ? <img src={item.url} alt={item.alt || item.title} className="h-16 w-full object-cover" /> : <div className="grid h-16 place-items-center bg-white text-2xl">{item.type === 'pdf' ? '📄' : '📎'}</div>}<p className="truncate px-2 py-1 text-[10px] font-bold">{item.title}</p></button>)}</div></div> }
function CardsEditor({ selectedSection, updateSection }) { if (!['cards', 'testimonials', 'timeline', 'accordion'].includes(selectedSection.type)) return null; return <div><Button tone="light" className="w-full" onClick={() => updateSection((section) => { section.content.cards = [...(section.content.cards || []), createCard()] })}>Add card</Button></div> }
function ButtonsEditor({ selectedSection, updateSection }) { return <div><Button tone="light" className="w-full" onClick={() => updateSection((section) => { section.content.buttons = [...(section.content.buttons || []), createButton()] })}>Add button</Button></div> }
