import { useMemo, useState } from 'react'
import { fileKind } from '../../lib/validation/sanitize'
import { Button, TextInput } from './ui.jsx'
export default function MediaLibraryPanel({ site, commit, onSelect, notify }) {
  const [query, setQuery] = useState('')
  const [uploading, setUploading] = useState(false)
  const [selectedId, setSelectedId] = useState('')
  const items = useMemo(() => site.media.filter((item) => `${item.title} ${item.url}`.toLowerCase().includes(query.toLowerCase())), [site.media, query])
  async function upload(event) { const file = event.target.files[0]; if (!file) return; setUploading(true); try { const response = await fetch('/api/upload', { method: 'POST', headers: { 'content-type': file.type, 'x-file-name': file.name }, body: file }); const data = await response.json(); if (!response.ok) throw new Error(data.error); commit((draft) => draft.media.push({ id: crypto.randomUUID(), ...data, type: fileKind(data.mimeType), alt: '', caption: '', createdAt: new Date().toISOString() })); notify?.('Upload complete') } catch (error) { notify?.(error.message || 'Upload failed', 'error'); alert(error.message) } finally { setUploading(false); event.target.value = '' } }
  return <div className="mt-5"><TextInput placeholder="Search images, PDFs, files…" value={query} onChange={(event) => setQuery(event.target.value)} /><label className={`mt-3 flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-dashed p-4 text-center text-sm font-black transition-all active:scale-[0.98] ${uploading ? 'border-slate-300 bg-slate-100 text-slate-500' : 'border-sky-300 bg-sky-50 text-sky-700 hover:border-sky-500 hover:bg-sky-100'}`}>{uploading && <span className="h-4 w-4 animate-spin rounded-full border-2 border-current border-t-transparent" />}{uploading ? 'Uploading…' : 'Upload media'}<input type="file" className="hidden" disabled={uploading} onChange={upload} /></label><div className="mt-4 grid grid-cols-2 gap-3">{items.map((item) => <button key={item.id} onClick={() => { setSelectedId(item.id); onSelect?.(item.id); notify?.('Media selected') }} className={`cursor-pointer overflow-hidden rounded-2xl border bg-white text-left shadow-sm transition-all hover:-translate-y-1 hover:border-sky-500 hover:shadow-lg active:scale-95 focus-visible:outline focus-visible:outline-2 focus-visible:outline-sky-400 ${selectedId === item.id ? 'border-sky-500 ring-4 ring-sky-100' : 'border-slate-200'}`}>{item.type === 'image' ? <img src={item.url} alt={item.alt || item.title} className="h-28 w-full object-cover" /> : <div className="grid h-28 place-items-center bg-slate-100 text-4xl">{item.type === 'pdf' ? '📄' : item.type === 'video' ? '🎬' : '📎'}</div>}<div className="p-3"><p className="truncate text-xs font-black">{item.title}</p><p className="text-[10px] uppercase text-slate-500">Click to use</p></div></button>)}</div></div>
}
