import { useMemo, useState } from 'react'
import { fileKind } from '../../lib/validation/sanitize'
import { Button, TextInput } from './ui.jsx'
export default function MediaLibraryPanel({ site, commit, onSelect }) {
  const [query, setQuery] = useState('')
  const items = useMemo(() => site.media.filter((item) => `${item.title} ${item.url}`.toLowerCase().includes(query.toLowerCase())), [site.media, query])
  async function upload(event) { const file = event.target.files[0]; if (!file) return; try { const response = await fetch('/api/upload', { method: 'POST', headers: { 'content-type': file.type, 'x-file-name': file.name }, body: file }); const data = await response.json(); if (!response.ok) throw new Error(data.error); commit((draft) => draft.media.push({ id: crypto.randomUUID(), ...data, type: fileKind(data.mimeType), alt: '', caption: '', createdAt: new Date().toISOString() })) } catch (error) { alert(error.message) } }
  return <div className="mt-5"><TextInput placeholder="Search images, PDFs, files…" value={query} onChange={(event) => setQuery(event.target.value)} /><label className="mt-3 block cursor-pointer rounded-2xl border border-dashed border-sky-300 bg-sky-50 p-4 text-center text-sm font-black text-sky-700">Upload media<input type="file" className="hidden" onChange={upload} /></label><div className="mt-4 grid grid-cols-2 gap-3">{items.map((item) => <button key={item.id} onClick={() => onSelect?.(item.id)} className="overflow-hidden rounded-2xl border border-slate-200 bg-white text-left shadow-sm transition hover:-translate-y-1 hover:border-sky-500 hover:shadow-lg">{item.type === 'image' ? <img src={item.url} alt={item.alt || item.title} className="h-28 w-full object-cover" /> : <div className="grid h-28 place-items-center bg-slate-100 text-4xl">{item.type === 'pdf' ? '📄' : item.type === 'video' ? '🎬' : '📎'}</div>}<div className="p-3"><p className="truncate text-xs font-black">{item.title}</p><p className="text-[10px] uppercase text-slate-500">Click to use</p></div></button>)}</div></div>
}
