import { useState } from 'react'
import { Button, Field, TextInput } from './ui.jsx'

function navChildren(items, parentId) { return items.filter((item) => (item.parentId || '') === (parentId || '')).sort((a, b) => (a.order || 0) - (b.order || 0)) }
export default function NavigationPanel({ site, commit }) {
  const [mode, setMode] = useState('desktop')
  const addLink = () => commit((draft) => draft.navigation.push({ id: crypto.randomUUID(), label: 'New link', href: '/', linkType: 'internal', target: '_self', hidden: false, order: draft.navigation.length + 1, children: [] }))
  return <div className="mt-5 max-h-[calc(100vh-9rem)] space-y-4 overflow-y-auto pr-2 pb-8"><div className="grid grid-cols-2 gap-2"><Button tone={mode === 'desktop' ? 'blue' : 'light'} onClick={() => setMode('desktop')}>Desktop menu</Button><Button tone={mode === 'mobile' ? 'blue' : 'light'} onClick={() => setMode('mobile')}>Mobile menu</Button></div><Button tone="blue" className="w-full" onClick={addLink}>+ Add custom link</Button><div className="rounded-2xl bg-slate-50 p-3 text-sm text-slate-500">Drag a menu item onto another item to nest it as a submenu. Toggle visibility without deleting the page.</div><div className="space-y-2"><NavigationTree items={site.navigation} allItems={site.navigation} parentId="" level={0} commit={commit} pages={site.pages} /></div><div className="rounded-2xl border border-slate-200 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">Preview</p><div className={`mt-3 flex ${mode === 'mobile' ? 'flex-col' : 'flex-wrap'} gap-2`}>{site.navigation.filter((item) => !item.hidden && !item.parentId).map((item) => <span key={item.id} className="rounded-full bg-white px-3 py-2 text-sm font-bold shadow-sm">{item.label}</span>)}</div></div></div>
}
function NavigationTree({ items, allItems, parentId, level, commit, pages }) {
  return navChildren(items, parentId).map((item, index) => <NavigationItem key={item.id} item={item} index={index} allItems={allItems} level={level} commit={commit} pages={pages} />)
}
function NavigationItem({ item, index, allItems, level, commit, pages }) {
  const children = navChildren(allItems, item.id)
  return <div><div draggable onDragStart={(event) => event.dataTransfer.setData('nav/id', item.id)} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const id = event.dataTransfer.getData('nav/id'); if (id && id !== item.id) commit((draft) => { const dragged = draft.navigation.find((entry) => entry.id === id); dragged.parentId = item.id }) }} style={{ marginLeft: level * 14 }} className="rounded-2xl border border-slate-200 bg-white p-3 shadow-sm transition hover:border-sky-300 hover:shadow"><div className="flex items-center gap-2"><span className="cursor-grab text-slate-400">⋮⋮</span><TextInput value={item.label} onChange={(event) => commit((draft) => { draft.navigation.find((entry) => entry.id === item.id).label = event.target.value })} /><Button tone="light" onClick={() => commit((draft) => { const entry = draft.navigation.find((nav) => nav.id === item.id); entry.hidden = !entry.hidden })}>{item.hidden ? 'Show' : 'Hide'}</Button><Button tone="red" onClick={() => confirm(`Delete menu item "${item.label}"?`) && commit((draft) => { draft.navigation = draft.navigation.filter((entry) => entry.id !== item.id && entry.parentId !== item.id) })}>Delete</Button></div><div className="mt-2 grid grid-cols-[1fr_auto] gap-2"><Field label="Link"><TextInput value={item.href || ''} onChange={(event) => commit((draft) => { draft.navigation.find((entry) => entry.id === item.id).href = event.target.value })} /></Field><Field label="Page"><select className="w-full rounded-xl border border-slate-200 p-2 text-sm" onChange={(event) => event.target.value && commit((draft) => { const page = draft.pages.find((p) => p.id === event.target.value); const entry = draft.navigation.find((nav) => nav.id === item.id); entry.href = `/${page.slug}`; entry.label = page.title })}><option value="">Link page…</option>{pages.map((page) => <option key={page.id} value={page.id}>{page.title}</option>)}</select></Field></div></div>{children.length > 0 && <div className="ml-4 border-l border-slate-200 pl-2"><NavigationTree items={allItems} allItems={allItems} parentId={item.id} level={level + 1} commit={commit} pages={pages} /></div>}</div>
}
