export const clone = (value) => JSON.parse(JSON.stringify(value))
export function Button({ children, tone = 'dark', className = '', loading = false, disabled = false, ...props }) {
  const tones = { dark: 'bg-slate-950 text-white shadow-slate-950/20 hover:bg-slate-800', light: 'border border-slate-200 bg-white text-slate-700 hover:border-sky-300 hover:bg-sky-50', ghost: 'bg-white/10 text-white hover:bg-white/20', green: 'bg-emerald-600 text-white shadow-emerald-600/20 hover:bg-emerald-500', red: 'bg-red-600 text-white shadow-red-600/20 hover:bg-red-500', blue: 'bg-sky-600 text-white shadow-sky-600/20 hover:bg-sky-500' }
  return <button {...props} disabled={disabled || loading} className={`inline-flex cursor-pointer items-center justify-center gap-2 rounded-xl px-3 py-2 text-sm font-bold shadow-sm transition-all duration-150 ease-out hover:-translate-y-0.5 hover:shadow-lg active:translate-y-0 active:scale-95 active:shadow-inner focus-visible:outline focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-sky-400 disabled:pointer-events-none disabled:cursor-not-allowed disabled:opacity-50 ${tones[tone]} ${className}`}>{loading && <span className="h-3.5 w-3.5 animate-spin rounded-full border-2 border-current border-t-transparent" />}{children}</button>
}
export function Field({ label, children }) { return <label className="block"><span className="mb-1 block text-[11px] font-black uppercase tracking-wide text-slate-500">{label}</span>{children}</label> }
export function TextInput(props) { return <input {...props} className={`w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:border-sky-500 focus:ring-2 focus:ring-sky-100 ${props.className || ''}`} /> }
export function TextArea(props) { return <textarea {...props} className="min-h-24 w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm outline-none transition focus:border-sky-500 focus:ring-2 focus:ring-sky-100" /> }
export function setPath(obj, path, value) { const parts = path.split('.'); let cur = obj; parts.slice(0, -1).forEach((part) => { cur = cur[part] }); cur[parts.at(-1)] = value }
